
spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/vancol_db
    username: vancol_user
    password: vancol_pass
